
penapi: 3.0.0
info:
  title: app
  version: 1.0
paths:
  /:
    get:
      summary: Hoge API
      responses:
        "200":
          description: ok
          content:
            application/json:
              schema:
                type: object
                properties:
                  payload:
                    type: object
        "400":
          description: Bad Request
      parameters:
        - schema:
            type: string
          in: header
          name: authorization
          required: true

